### ISSUE TITLE
Hello sir I wanted to use your touch controls but I don't know how to please help me

### ISSUE THREAD

**Issue by blaxezcode** [mese79/TouchControls#1]

**Comment by mese79** [comment]
Hi  
There is an `example.js` in `js` folder you can see how to use Touch Controls.  
[example.js](https://github.com/mese79/TouchControls/blob/49d0bcb365c57cabd160fca2d9c4c9e82e456d3a/js/example.js#L65)

**Comment by blaxezcode** [comment]
Still not figured out can you implement it on a simple scene will a plane
that would be a great help sir
