### ISSUE TITLE
No Lisense

### ISSUE THREAD

**Issue by sasial-dev** [mese79/TouchControls#3]
A lisense is needed so we can use this in OSS projects!
I've created a fork with the code updates for TS & the newest version of three.js and I need this code lisenced so I can properly publish it :)

**Comment by mese79** [comment]
Nice!!
MIT license was added.

**Comment by sasial-dev** [comment]
Thank you!
Do you want me to PR the TS work back into this repo?

**Comment by mese79** [comment]
Actually I am about to make some time to update the code but I'd prefer an ES6 update.
I can make a branch for TS though.
